// Global
export const SET_LOADING = "SET_LOADING";
export const SET_ERROR = "SET_ERROR";
export const SET_SUCCESS = "SET_SUCCESS";

//Client
export const GET_CLIENTS = "GET_CLIENTS";
export const ADD_CLIENT = "ADD_CLIENT";
export const REMOVE_CLIENT = "REMOVE_CLIENT";
export const EDIT_CLIENT = "EDIT_CLIENT";
export const SET_ISOPENMODAL = "SET_ISOPENMODAL";
export const SET_ISOPENCONFIRMMODAL = "SET_ISOPENCONFIRMMODAL";
export const SET_EDITABLE_CLIENT = "SET_EDITABLE_CLIENT";

//ClientModal
export const RESET_MODAL_DATA = "RESET_MODAL_DATA";
export const SET_INITIALSTATE = "SET_INITIALSTATE";
export const CHANGE_MODAL_FORM = "CHANGE_MODAL_FORM";

//Provider
export const GET_PROVIDERS = "GET_PROVIDERS";
export const ADD_PROVIDER = "ADD_PROVIDER";
export const EDIT_PROVIDER = "EDIT_PROVIDER";
export const REMOVE_PROVIDER = "REMOVE_PROVIDER";
export const TOGGLE_CHECKED = "TOGGLE_CHECKED";
export const SET_EDITABLE_PROVIDER = "SET_EDITABLE_PROVIDER";
export const CHANGE_PROVIDER = "CHANGE_PROVIDER";
export const RESET_PROVIDER = "RESET_PROVIDER";

//Search
export const CHANGE_SEARCH_VALUE = "CHANGE_SEARCH_VALUE";
export const SET_DROPDOWN_VALUE = "SET_DROPDOWN_VALUE";
export const SET_DATEPICKER_DATE = "SET_DATEPICKER_DATE";
export const RESET_SEARCH_DATA = "RESET_SEARCH_DATA";
export const TOGGLE_CLICK = "TOGGLE_CLICK";
